// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gearworks.proto
// Protobuf Java Version: 4.27.3

package com.gearworkssmp.gwsync;

public final class GWSync {
  private GWSync() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      GWSync.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gearworks_SaveStateRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gearworks_SaveStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gearworks_SaveStateReply_descriptor;
  static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gearworks_SaveStateReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gearworks_LoadStateRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gearworks_LoadStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gearworks_LoadStateReply_descriptor;
  static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gearworks_LoadStateReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gearworks_ChatMessage_descriptor;
  static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gearworks_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017gearworks.proto\022\tgearworks\"#\n\020SaveStat" +
      "eRequest\022\017\n\007user_id\030\001 \001(\t\"!\n\016SaveStateRe" +
      "ply\022\017\n\007user_id\030\001 \001(\t\"#\n\020LoadStateRequest" +
      "\022\017\n\007user_id\030\001 \001(\t\"!\n\016LoadStateReply\022\017\n\007u" +
      "ser_id\030\001 \001(\t\"A\n\013ChatMessage\022\017\n\007user_id\030\001" +
      " \001(\t\022\020\n\010username\030\002 \001(\t\022\017\n\007message\030\003 \001(\t2" +
      "\344\001\n\004Sync\022K\n\017SavePlayerState\022\033.gearworks." +
      "SaveStateRequest\032\031.gearworks.SaveStateRe" +
      "ply\"\000\022K\n\017LoadPlayerState\022\033.gearworks.Loa" +
      "dStateRequest\032\031.gearworks.LoadStateReply" +
      "\"\000\022B\n\nHandleChat\022\026.gearworks.ChatMessage" +
      "\032\026.gearworks.ChatMessage\"\000(\0010\001BM\n!com.ge" +
      "arworkssmp.gearworks.gwsyncB\006GWSyncP\001Z\036g" +
      "ithub.com/gearworkssmp/gwsyncb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gearworks_SaveStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gearworks_SaveStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gearworks_SaveStateRequest_descriptor,
        new String[] { "UserId", });
    internal_static_gearworks_SaveStateReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gearworks_SaveStateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gearworks_SaveStateReply_descriptor,
        new String[] { "UserId", });
    internal_static_gearworks_LoadStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gearworks_LoadStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gearworks_LoadStateRequest_descriptor,
        new String[] { "UserId", });
    internal_static_gearworks_LoadStateReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gearworks_LoadStateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gearworks_LoadStateReply_descriptor,
        new String[] { "UserId", });
    internal_static_gearworks_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gearworks_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gearworks_ChatMessage_descriptor,
        new String[] { "UserId", "Username", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
